run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - gosec
    - prealloc
    - exportloopref
    - gocritic
    - revive
    - errorlint

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for CLI apps

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/vburojevic/xcw

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - paramTypeCombine
      - unnamedResult

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104  # Unhandled errors (we check errcheck)
      - G304  # File path from variable (necessary for CLI)

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false

  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude known issues in generated/vendor code
    - path: vendor/
      linters:
        - all

    # Allow fmt.Errorf without wrapping in some cases
    - linters:
        - errorlint
      text: "non-wrapping format verb"

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
